### ISSUE TITLE
Duplicated Card in Hand

### ISSUE THREAD

**Issue by rubenpieters** [jaspervdj/uplcg#2]
I managed to receive a hand with a duplicated card, which I assume is not intended. While proposing the card, it selects both instances (as seen in the picture) and when confirming the propose it consumed both instances.

![duplicated](https://user-images.githubusercontent.com/2465652/91097946-e2877b00-e660-11ea-9c92-75e605342f7a.PNG)

**Comment by jaspervdj** [comment]
Thanks for reporting this!  I'll have a look later this week.  The obvious solution is to keep pulling new cards until you get one that's not in your hand, but that risks an infinite recursion if the number of cards is smaller than the hand size, so I probably need to add an additional check for that as well.
